function edgePolys = GetVoronoiEdges(vorVertices,vorCenters,vorIndices)

% Algorithm: if cell has a vertex wich is beyond the max of the centers
% (assumes voronoi tesselation will add points way away from the seed points
xOutRange = cell2mat(cellfun(@(x)...
    any(vorVertices(x,1)<min(vorCenters(:,1))) | any(vorVertices(x,1)>max(vorCenters(:,1))),...
    vorIndices,'UniformOutput',false));
yOutRange = cell2mat(cellfun(@(x)...
    any(vorVertices(x,2)<min(vorCenters(:,2))) | any(vorVertices(x,2)>max(vorCenters(:,2))),...
    vorIndices,'UniformOutput',false));
edgePolys = xOutRange | yOutRange;

end